### ISSUE TITLE
Your project brianfrankcooper/YCSB is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [brianfrankcooper/YCSB#1274]
Hi, there!

We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.

We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.

1. org.apache.logging.log4j log4j-core(ignite/pom.xml)
version: 2.11.0

Jira issues:
Log4j2 throws NoClassDefFoundError in Java 9
affectsVersions:2.10.0,2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2129?filter=allopenissues
Empty Automatic-Module-Name Header
affectsVersions:2.10.0,2.11.0,3.0.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2254?filter=allopenissues
gc-free mixed async loging loses parameter values after the first appender
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2301?filter=allopenissues
Log4j 2.10+not working with SLF4J 1.8 in OSGI environment
affectsVersions:2.10.0,2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2305?filter=allopenissues
AsyncQueueFullMessageUtil causes unparsable message output
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2318?filter=allopenissues
AbstractLogger NPE hides actual cause when getFormat returns null
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2320?filter=allopenissues
AsyncLogger without specifying a level always uses ERROR
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2321?filter=allopenissues
Errors thrown in formatting may stop background threads
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2333?filter=allopenissues
JsonLayout not working with AsyncLoggerContextSelector in 2.11.0
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2341?filter=allopenissues
Typo in log4j-api Activator
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2343?filter=allopenissues
PropertiesUtil.reload() might throw NullPointerException
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2355?filter=allopenissues
NameAbbreviator skips first fragments
affectsVersions:2.11.0,2.11.1
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2365?filter=allopenissues
Outputs wrong message when used within overridden Throwable method
affectsVersions:2.8.1,2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2368?filter=allopenissues
StringBuilder escapeJson performs unnecessary Memory Allocations
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2373?filter=allopenissues
fix the CacheEntry map in ThrowableProxy#toExtendedStackTrace to be put and gotten with same key
affectsVersions:2.6.2,2.7,2.8,2.8.1,2.8.2,2.9.0,2.9.1,2.10.0,2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2389?filter=allopenissues
Fix incorrect links in Log4j web documentation.
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2390?filter=allopenissues

2. org.apache.httpcomponents httpclient(rest/pom.xml, arangodb/pom.xmll)
version: 4.5.1

Jira issues:
Add convenience methods to fluent API class Request
affectsVersions:4.5.1
https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1696?filter=allopenissues
GET request should support body
affectsVersions:4.5.1
https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1703?filter=allopenissues
Delete obsolete clone method
affectsVersions:4.5.1
https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1709?filter=allopenissues
NTLMEngineImpl.Type1Message not thread safe but declared as a constant
affectsVersions:4.5.1
https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1715?filter=allopenissues
HttpClient 4.5.1 may perform multiple requests on the same connection despite having "Connection: close" header.
affectsVersions:4.5.1
https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1723?filter=allopenissues
The deprecated SSLSocketFactory does not contain the SNI fix found in the SSLConnectionSocketFactory class
affectsVersions:4.4.1;4.5.1
https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1726?filter=allopenissues
org.apache.http.impl.client.AbstractHttpClient#createClientConnectionManager Does not account for context class loader
affectsVersions:4.4.1;4.5;4.5.1;4.5.2
https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1727?filter=allopenissues
Malformed path not handled well
affectsVersions:4.5.1
https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1803?filter=allopenissues
NTLM authentication error: Unexpected state: MSG_TYPE3_GENERATED
affectsVersions:4.5.1
https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1882?filter=allopenissues

3. commons-codec commons-codec(solr/pom.xml)
version: 1.10

Jira issues:
Bug in HW rule in Soundex
affectsVersions:1.10
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-199?filter=allopenissues
Charsets Javadoc breaks build when using Java 8
affectsVersions:1.10
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-207?filter=allopenissues
Javadoc for SHA-224 DigestUtils methods should mention Java 1.8.0 restriction instead of 1.4.0
affectsVersions:1.10
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-209?filter=allopenissues
Don't deprecate Charsets Charset constants in favor of Java 7's java.nio.charset.StandardCharsets
affectsVersions:1.10
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-219?filter=allopenissues
HmacUtils.updateHmac calls reset() unnecessarily
affectsVersions:1.10
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-221?filter=allopenissues
InputStream not closed
affectsVersions:1.10;1.11
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-225?filter=allopenissues
StringUtils.newStringxxx(null) should return null; not NPE
affectsVersions:1.10
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-229?filter=allopenissues
URLCodec.WWW_FORM_URL should be private
affectsVersions:1.10
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-230?filter=allopenissues
StringUtils.equals(CharSequence cs1; CharSequence cs2) can fail with String Index OBE
affectsVersions:1.10
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-231?filter=allopenissues
URLCodec is neither immutable nor threadsafe
affectsVersions:1.10
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-232?filter=allopenissues

4. org.slf4j slf4j-api(kudu/pom.xml)
version: 1.7.21

Jira issues:
Cannot re-initialize the SimpleLogger anymore.
affectsVersions:1.7.21
https://jira.qos.ch/projects/SLF4J/issues/SLF4J-370?filter=allopenissues
Marker lost in EventRecodingLogger
affectsVersions:1.7.21
https://jira.qos.ch/projects/SLF4J/issues/SLF4J-379?filter=allopenissues
Support for JCL 1.2
affectsVersions:1.7.21
https://jira.qos.ch/projects/SLF4J/issues/SLF4J-383?filter=allopenissues

5. org.slf4j slf4j-simple(ignite/pom.xml,cassandra/pom.xml)
version: 1.7.21

Jira issues:
Cannot re-initialize the SimpleLogger anymore.
affectsVersions:1.7.21
https://jira.qos.ch/projects/SLF4J/issues/SLF4J-370?filter=allopenissues
Marker lost in EventRecodingLogger
affectsVersions:1.7.21
https://jira.qos.ch/projects/SLF4J/issues/SLF4J-379?filter=allopenissues
Support for JCL 1.2
affectsVersions:1.7.21
https://jira.qos.ch/projects/SLF4J/issues/SLF4J-383?filter=allopenissues

6. org.apache.logging.log4j log4j-core(elasticsearch5/pom.xml)
version: 2.8.2

Jira issues:
Update JavaMail from 1.5.5 to 1.5.6
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1872?filter=allopenissues
Unreliable checking for runtime dependencies
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1876?filter=allopenissues
documentation error regarding additivity default value
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1885?filter=allopenissues
Log4j throws a java.nio.charset.UnsupportedCharsetException: cp65001
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1888?filter=allopenissues
Nullpointer with DirectWriteRolloverStrategy
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1916?filter=allopenissues
EOFException with FormattedMessage
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1929?filter=allopenissues
JMS Appender does not know how to recover from a broken connection
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1934?filter=allopenissues
RFC5424 Layout ignores event prefix
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1943?filter=allopenissues
Trim levels read from properties file to remove trailing spaces
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1948?filter=allopenissues
JndiManager is not released when the JmsAppender builder catches an exception trying to build itself
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1953?filter=allopenissues
Dynamic reconfiguration does not work for filePattern of RollingFile
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1964?filter=allopenissues
GelfLayout/SocketAppender does document "includeNullDelimiter" to append the frame delimiter null byte when using TCP
affectsVersions:2.8;2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1968?filter=allopenissues
Log4j-config.xsd only allows one AppenderRef element for each Logger element
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1982?filter=allopenissues
Fix default buffer size to match documentation (from 8102 to 8192 a.k.a. 8KB)
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1985?filter=allopenissues
Log4J JUL Bridge and RMI Security Manager causes access denied ("java.util.logging.LoggingPermission" "control")
affectsVersions:2.7;2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1987?filter=allopenissues
DefaultConfigurationBuilder.writeXmlAttributes does not handle null attribute values
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2002?filter=allopenissues
SslSocketManager does not apply SSLContext on TCP reconnect
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2013?filter=allopenissues
LoggerNameLevelRewritePolicy documentation is wrong; example is broken
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2018?filter=allopenissues
Messages appear out of order in log file (was: Log4j2 log file not reflecting application log function calls)
affectsVersions:2.8.2;2.9.0;2.9.1
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2031?filter=allopenissues
Curly braces in parameters are treated as placeholders
affectsVersions:2.8.2;2.9.0;2.10.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2032?filter=allopenissues
AbstactDatabase appender issue with AsyncLogger
affectsVersions:2.8.1;2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2060?filter=allopenissues
Log4j1XmlLayout does not provide the entire stack trace; it is missing the caused by information
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2070?filter=allopenissues
ReusableParametrizedMessages keeps references to objects beyond their expected lifetime
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2201?filter=allopenissues
Configuration builder classes should look for "onMismatch"; not "onMisMatch".
affectsVersions:2.4;2.4.1;2.5;2.6;2.6.1;2.6.2;2.7;2.8;2.8.1;2.8.2;2.9.0;2.10.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2219?filter=allopenissues
Log4j2 2.8.2 JMX unregister NullPointerException
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2304?filter=allopenissues
fix the CacheEntry map in ThrowableProxy#toExtendedStackTrace to be put and gotten with same key
affectsVersions:2.6.2;2.7;2.8;2.8.1;2.8.2;2.9.0;2.9.1;2.10.0;2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2389?filter=allopenissues
Handle some unchecked exceptions while loading plugins
affectsVersions:2.8.2
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2422?filter=allopenissues

7. ch.qos.logback logback-classic(mongodb/pom.xml)
version: 1.1.2

Jira issues:
ConfigurationDelegate.groovy should check AppenderAttachable not AsyncAppender
affectsVersions:1.1.2
https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1008?filter=allopenissues
NullPointerException from RollingFileAppender
affectsVersions:1.1.2
https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1054?filter=allopenissues
DatePatternToRegexTest fails on non English locale
affectsVersions:1.1.2
https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-969?filter=allopenissues
Require JDK 1.6 to run logback
affectsVersions:1.1.2
https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-972?filter=allopenissues

8. ch.qos.logback logback-classic(arangodb/pom.xml)
version: 1.1.3

Jira issues:
release process fails with version 2.10.1 of maven-javadoc-plugin
affectsVersions:1.1.3
https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1062?filter=allopenissues
 JaninoEventEvaluatorTest and MDCBasedDiscriminatorTest fail under Linux
affectsVersions:1.1.3
https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1063?filter=allopenissues
Unable to set string properties to json strings with nested nodes
affectsVersions:1.1.3
https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1101?filter=allopenissues
ConsoleAppender does not report the correct ConsoleTarget values in case of problem
affectsVersions:1.1.3
https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1132?filter=allopenissues
CharSequenceToRegexMapper#findMinMaxLengthsInSymbols() always returns min=0 
affectsVersions:1.1.3
https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-971?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019
