### PR TITLE
Proof-Of-Concept for folding the YCSB-TS fork back into YCSB after #1008 [WIP]

### PR DESCRIPTION
**Pull request by Vogel612**
This PullRequest is a continued development of the work performed by Andreas Bader in https://github.com/TSDBBench/YCSB-TS.

For authorship reasons the commits are currently split like this. In addition: since the language-binding for influxdb requires java 8, this pull-request also drops JDK 7 support.

There are some uncertainties for me in regards to how the binding should behave in certain situations. These are marked in InfluxDBClient.java with FIXME comments.
Guidance is very much appreciated.

Do also note that the DELETE operation was not supported (or required) in the benchmarking performed for YCSB-TS. I will amend the PullRequest to include an implementation for that operation

### CODE REVIEW

**Comment by Vogel612** [comment]
bump: Pull request is ready for review since almost a month :)

**Comment by manolama** [comment]
Hi @Vogel612 Thanks for this! I didn't even know it was out there and had started TS work that's in 0.13 already. Let me look and see what it would take to merge the loads.

**Comment by Vogel612** [comment]
@manolama as of now I'm not looking to merge the workloads that have been introduced in YCSB-TS. The current work just leverages the API you have introduced in 035310c50dab7432771b5d0bc33ef4f2aaa67fde. 

Basically I'm checking out the newly created bindings on top of the current `master` tip and perform some basic maintenance.
This includes the following actions:

- Inherit from a `TimeseriesDB` class derived from `DB` that performs the unwrapping of timeseries queries
- Fix compilation errors (old code uses `int` status codes instead of `Status`)
- Fix possible checkstyle violations
- Add binding to `root` and `ycsb-distribution`, as well as `/bin/ycsb`
- Add License Headers and `package-info.java`

All this is then commited with @baderas as author

To finalize a binding, the following steps are then performed:

- Add and write  'README.md` for binding
- Update property read behaviour
- Possibly perform minor readability refactorings 

This is then committed under my name.

The following bindings are still outstanding to go through that process:

```text
druid
gnocchi
graphite
h5serv
hana
kairosdb
kdbplus
kudu
newts
prometheus
rhombus
seriesly
``` 

for specific information about how the workloads were changed and / or intended, I highly recommend contacting @baderas

**Comment by manolama** [comment]
Thanks @Vogel612. Can we drop this PR and split it into individual PRs, one per binding and one for any [core] changes that are required? 

Do we have permission from @baderas to merge this upstream? 

And can these use the new https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/workloads/TimeSeriesWorkload.java?

**Comment by Vogel612** [comment]
> Can we drop this PR and split it into individual PRs, one per binding and one for any [core] changes that are required?

Sure we can, I'd personally prefer to keep this PR open as signpost though. This allows linking the newly created PRs back here and ensure that all changes are actually incorporated.

In addition this PR is somewhat WIP in the first place. There's still a number of outstanding bindings.

> Do we have permission from @baderas to merge this upstream?

In the downstream fork, there has been a short discussion about updating the downstream fork. There I had brought up the idea of merging to upstream instead. 
Since @baderas did not voice any objections I would consider that an okay. 

> Can these use the new `TimeSeriesWorkload`?

I've verified that `tsworkloada` is executed with the [influxdb] binding. All workload-handling logic has been split into the abstract class `TimeSeriesDB`, see 01409fadd4feffb6eb55ba00f87b3db4f3e0892e.  
I understand that is not a guarantee, but I did not verify all bindings, I've just been deriving them from `TimeSeriesDB`

**Comment by baderas** [comment]
Yes, you have the permission to merge it back to YCSB. So no problem from my side :+1:

**Comment by Vogel612** [comment]
Hey @manolama 
I was wondering whether you'd seen the [core] PR that I opened in response to your earlier comment.

It's somewhat discouraging for an expected and requested PR to have no reaction at all for a week ...
I did ping you in the PR, but haven't heard from you, so I'm trying here.

Greetings, Vogel

**Comment by Vogel612** [comment]
### Current status:

All bindings have been moved over and are compiling. That does specifically not mean that they are all verified to be working or even expected to be working.

The following bindings will need further work, in most cases because they need to know during initialization which possible values can be generated for their tags and how many tags there can be:

```text
databus
h5serv
rhombus
```

The following bindings are still waiting on proper documentation to be added:

```
hana
kairosdb
kdbplus
newts
prometheus
rhombus
seriesly
```

Lastly, basically all bindings could use a full verification. This includes setting them up and doing a full testrun on them to verify they are working as expected.  
This last step will be part of the process of creating separate PullRequests for each of the bindings.


### Known issues

The `kdbplus-java` module used by `kdbplus` currently has some problems with how it's built. I'll investigate a bit into how I should set the target level for the maven-compiler-plugin so as to make the build pass on jdk9

**Comment by busbey** [comment]
is this obviated by #1095 or is there other work to do?

**Comment by Vogel612** [comment]
Hey @busbey #1095 just lays the groundwork for the separate bindings to be merged in.  What remains to be done is cherry-pick the separate bindings onto their own branches (preferrably off of master), verify they work and fix some possible errors.  
Additionally they need to deal with a minor change that was requested in the review by manolama. 

Lastly there's two bindings that are still missing docs (`rhombus` and `seriesly`).

I unfortunately will not be able to work on this for a while, I've been called to more immediately pressing tasks. With this explanation it should be rather clear what's left to be done.
